import React from "react";
import Head from "next/head";
import Paragraph from "../components/paragraph";
import useSWR from "swr";
import Loader from "../components/loader";

const TEXT =
  "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet";

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  const { data, error } = useSWR(
    "https://baconipsum.com/api/?type=all-meat&sentences=20&start-with-lorem=1",
    fetcher
  );

  if (error)
    return (
      <>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Paragraph randomParagraph={TEXT.trim()} />
      </>
    );

  return !data ? (
    <Loader />
  ) : (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paragraph randomParagraph={data[0] || TEXT.trim()} />
    </>
  );
}
